ALTER TABLE users ADD COLUMN IF NOT EXISTS phone VARCHAR(20) NULL COMMENT '휴대전화 번호';
ALTER TABLE users ADD COLUMN IF NOT EXISTS birthDate DATE NULL COMMENT '생년월일 (YYYY-MM-DD)';
ALTER TABLE users ADD COLUMN IF NOT EXISTS gender ENUM('male', 'female') NULL COMMENT '성별';
ALTER TABLE users ADD COLUMN IF NOT EXISTS avatarUrl VARCHAR(255) NULL COMMENT '아바타 프리셋 URL 또는 preset:id:emoji';
ALTER TABLE users ADD COLUMN IF NOT EXISTS learningGoal JSON NULL COMMENT '학습 목적 (배열)';
